// Generated by IcedCoffeeScript 108.0.9
(function() {
  var ArrayType, ArrayValue, Decorator, Enum, Field, Fixed, Identifier, Import, Message, Node, Param, Protocol, ProtocolName, Record, String, Type, Union, Value,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Node = (function() {
    function Node(_arg) {
      this.start = _arg.start, this.end = _arg.end;
    }

    Node.prototype.is_import = function() {
      return false;
    };

    return Node;

  })();

  Protocol = (function(_super) {
    __extends(Protocol, _super);

    function Protocol(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.label = _arg.label, this.statements = _arg.statements;
      Protocol.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    Protocol.prototype.get_imports = function() {
      var i;
      return (function() {
        var _i, _len, _ref, _results;
        _ref = this.statements;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          if (i.is_import()) {
            _results.push(i);
          }
        }
        return _results;
      }).call(this);
    };

    return Protocol;

  })(Node);

  ProtocolName = (function(_super) {
    __extends(ProtocolName, _super);

    function ProtocolName(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.name = _arg.name, this.decorators = _arg.decorators;
      ProtocolName.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return ProtocolName;

  })(Node);

  Decorator = (function(_super) {
    __extends(Decorator, _super);

    function Decorator(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.label = _arg.label, this.args = _arg.args;
      Decorator.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Decorator;

  })(Node);

  Identifier = (function(_super) {
    __extends(Identifier, _super);

    function Identifier(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.name = _arg.name;
      Identifier.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Identifier;

  })(Node);

  Enum = (function(_super) {
    __extends(Enum, _super);

    function Enum(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.decorators = _arg.decorators, this.constants = _arg.constants;
      Enum.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Enum;

  })(Node);

  Record = (function(_super) {
    __extends(Record, _super);

    function Record(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.decorators = _arg.decorators, this.name = _arg.name, this.fields = _arg.fields;
      Record.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Record;

  })(Node);

  Field = (function(_super) {
    __extends(Field, _super);

    function Field(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.type = _arg.type, this.name = _arg.name;
      Field.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Field;

  })(Node);

  Type = (function(_super) {
    __extends(Type, _super);

    function Type(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.string = _arg.string, this.int = _arg.int, this.bool = _arg.bool, this.long = _arg.long, this.custom = _arg.custom, this.void_type = _arg.void_type, this.null_type = _arg.null_type;
      Type.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Type;

  })(Node);

  Value = (function(_super) {
    __extends(Value, _super);

    function Value(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.int = _arg.int, this.string = _arg.string, this.bool = _arg.bool, this.null_value = _arg.null_value;
      Value.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Value;

  })(Node);

  ArrayType = (function(_super) {
    __extends(ArrayType, _super);

    function ArrayType(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.type = _arg.type;
      ArrayType.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return ArrayType;

  })(Node);

  Union = (function(_super) {
    __extends(Union, _super);

    function Union(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.types = _arg.types;
      Union.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Union;

  })(Node);

  Import = (function(_super) {
    __extends(Import, _super);

    function Import(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.type = _arg.type, this.path = _arg.path;
      Import.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    Import.prototype.is_import = function() {
      return true;
    };

    Import.prototype.set_protocol = function(ast) {
      return this.protocol = ast;
    };

    Import.prototype.get_path = function() {
      return this.path;
    };

    return Import;

  })(Node);

  Message = (function(_super) {
    __extends(Message, _super);

    function Message(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.decorators = _arg.decorators, this.name = _arg.name, this.params = _arg.params, this.return_type = _arg.return_type;
      Message.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Message;

  })(Node);

  Param = (function(_super) {
    __extends(Param, _super);

    function Param(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.type = _arg.type, this.name = _arg.name, this.def = _arg.def;
      Param.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Param;

  })(Node);

  ArrayValue = (function(_super) {
    __extends(ArrayValue, _super);

    function ArrayValue(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.type = _arg.type, this.name = _arg.name, this.def = _arg.def;
      ArrayValue.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return ArrayValue;

  })(Node);

  Fixed = (function(_super) {
    __extends(Fixed, _super);

    function Fixed(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.type = _arg.type, this.len = _arg.len;
      Fixed.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    return Fixed;

  })(Node);

  String = (function(_super) {
    __extends(String, _super);

    function String(_arg) {
      var end, start;
      start = _arg.start, end = _arg.end, this.type = _arg.type, this.val = _arg.val;
      String.__super__.constructor.call(this, {
        start: start,
        end: end
      });
    }

    String.prototype.eval_to_string = function() {
      return JSON.parse(this.val);
    };

    return String;

  })(Node);

  module.exports = {
    Protocol: Protocol,
    ProtocolName: ProtocolName,
    Decorator: Decorator,
    Identifier: Identifier,
    Enum: Enum,
    Record: Record,
    Field: Field,
    Type: Type,
    Value: Value,
    ArrayType: ArrayType,
    Union: Union,
    Import: Import,
    Message: Message,
    Param: Param,
    ArrayValue: ArrayValue,
    Fixed: Fixed,
    String: String
  };

}).call(this);
